name: Build & Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & test project
        run: dotnet test -c Release
      - name: Test creating package
        run: dotnet pack gsSlicer/gsSlicer.csproj 
               -c Release
               --include-source
               --include-symbols
               