name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git LFS pull
        run: git lfs pull
      - name: Build solution
        run: dotnet build -c Release
      - name: Unit tests
        run: dotnet test -c Release Sutro.Core.UnitTests/Sutro.Core.UnitTests.csproj --no-build
      - name: Functional tests
        run: dotnet test -c Release Sutro.Core.FunctionalTests/Sutro.Core.FunctionalTests.csproj --no-build