name: Publish

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git LFS pull
        run: git lfs pull
      - name: Build solution
        run: dotnet build -c Release
      - name: Unit tests
        run: dotnet test -c Release Sutro.Core.UnitTests/Sutro.Core.UnitTests.csproj --no-build
      - name: Functional tests
        run: dotnet test -c Release Sutro.Core.FunctionalTests/Sutro.Core.FunctionalTests.csproj --no-build 
      - name: Publish on version change
        id: publish_nuget
        uses: Elskom/publish-nuget@main
        with:
          # Relative to repository root
          PROJECT_FILE_PATH: Sutro.Core/Sutro.Core.csproj

          # Path to store all generated nuget packages, relative to root of repository
          PACKAGE_PATH: artifacts/

          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX: <Version>(.*)<\/Version>

          # Flag to enable / disable git tagging
          TAG_COMMIT: true

          # Format of the git tag, [*] gets replaced with version
          TAG_FORMAT: v*

          # nuget.org API key
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
